version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: certification_info
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro